name: vox-512-deeper-other

dataset_params:
  root_dir: ../data/vox512_filtered_webp
  frame_shape: 512,512,3
  id_sampling: True
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: True
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1


model_params:
  common_params:
    num_tps: 10
    num_channels: 3
    bg: True
    multi_mask: True
  generator_params:
    block_expansion: 64
    max_features: 512
    num_down_blocks: 4
    concat_encode: True
    skip_block_type: depthwise
    dropout: 0.1
  dense_motion_params:
    block_expansion: 64
    max_features: 1024
    num_blocks: 5
    scale_factor: 0.25 # might make sense to set to 0.5 because of the additional occlusion (4=>5)
    occlusion_num: 5

  avd_network_params:
    id_bottle_size: 128
    pose_bottle_size: 128


train_params:
  num_epochs: 30
  num_repeats: 5
  lr_generator: 2.0e-5
  lr_discriminator: 2.0e-5
  batch_size: 2
  scales: [1, 0.5, 0.25, 0.125]
  dataloader_workers: 8
  checkpoint_freq: 10
  dropout_epoch: 0
  dropout_maxp: 0.3
  dropout_startp: 0.1
  dropout_inc_epoch: 10
  bg_start: 101
  freeze_kp_detector: True
  freeze_bg_predictor: True
  freeze_dense_motion: False
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    perceptual: [10, 10, 10, 10, 10]
    equivariance_value: 10
    warp_loss: 10
    bg: 0
    l2: 0
    id: 1
    huber: 0
    generator_gan: 1
    generator_feat_match: 0
    discriminator_gan: 1
  optimizer: 'adamw'
  optimizer_params:
    betas: [ 0.9, 0.999 ]
    weight_decay: 1.0e-3
  scheduler: 'onecycle'
  scheduler_params:
    pct_start: 0.3


train_avd_params:
  num_epochs: 100
  num_repeats: 1
  batch_size: 8
  dataloader_workers: 6
  checkpoint_freq: 1
  epoch_milestones: [10, 20]
  lr: 1.0e-3
  lambda_shift: 1
  random_scale: 0.25

visualizer_params:
  kp_size: 5
  draw_border: True
  colormap: 'gist_rainbow'